# version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testdb #Postgres sẽ tạo database testdb ngay khi container được tạo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: huongduong/backend:${VERSION:-latest}
    # build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:123456@db:5432/testdb
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure 

  frontend:
    image: huongduong/frontend:${VERSION:-latest}
    # build: ./frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    expose:
      - "9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    expose:
      - "3001"
    volumes:
      - grafana-storage:/var/lib/grafana
    
volumes:
  grafana-storage:
